//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SageImportChecker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SageImportChecker.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous créer un fichier d&apos;exemple (o/n) ?.
        /// </summary>
        internal static string ConfigAskToWriteSample {
            get {
                return ResourceManager.GetString("ConfigAskToWriteSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier de configuration n&apos;exist pas.
        /// </summary>
        internal static string ConfigFileNotFound {
            get {
                return ResourceManager.GetString("ConfigFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier d&apos;exemple a été créé :.
        /// </summary>
        internal static string ConfigWriteSampleSuccess {
            get {
                return ResourceManager.GetString("ConfigWriteSampleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier n&apos;existe pas.
        /// </summary>
        internal static string FileDoesNotExists {
            get {
                return ResourceManager.GetString("FileDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargement de la configuration.
        /// </summary>
        internal static string LoadConfig {
            get {
                return ResourceManager.GetString("LoadConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargement du fichier d&apos;import Sage.
        /// </summary>
        internal static string LoadTextFile {
            get {
                return ResourceManager.GetString("LoadTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le matricule suivant n&apos;a pas été trouvé dans le fichier vérifiction csv:.
        /// </summary>
        internal static string MatriculeNotFoundInCsv {
            get {
                return ResourceManager.GetString("MatriculeNotFoundInCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le matricule suivant n&apos;a pas été trouvé dans le fichier d&apos;import sage : .
        /// </summary>
        internal static string MatriculeNotFoundInTxt {
            get {
                return ResourceManager.GetString("MatriculeNotFoundInTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} matricules trouvés.
        /// </summary>
        internal static string NbMatriculeLoaded {
            get {
                return ResourceManager.GetString("NbMatriculeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Valeurs à vérifier.
        /// </summary>
        internal static string NbValuesToCheck {
            get {
                return ResourceManager.GetString("NbValuesToCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appuyez sur une touche pour quitter.
        /// </summary>
        internal static string PressKeyToQuit {
            get {
                return ResourceManager.GetString("PressKeyToQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de configuration: .
        /// </summary>
        internal static string PromptConfigIdx {
            get {
                return ResourceManager.GetString("PromptConfigIdx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier de vérification CSV : .
        /// </summary>
        internal static string PromptCsvFile {
            get {
                return ResourceManager.GetString("PromptCsvFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier d&apos;import Sage : .
        /// </summary>
        internal static string PromptTextFile {
            get {
                return ResourceManager.GetString("PromptTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas de valeur pour la rubrique {0} sur le matricule {1}.
        /// </summary>
        internal static string RubricNotFound {
            get {
                return ResourceManager.GetString("RubricNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune erreur trouvée.
        /// </summary>
        internal static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
    }
}
